apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deployment
  namespace: test
  labels:
    app: health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
      - name: name-container
        image: manoj835/health:v5
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
          requests:
            memory: "100Mi"
            cpu: "50m"

